### ISSUE TITLE
Does it work with Azure DevOps authentication?

### ISSUE THREAD

**Issue by xperiandri** [Sebazzz/Return#1]
It would be extremely nice to have this as add-in of Azure DevOps

**Comment by Sebazzz** [comment]
Are you looking for SSO or a particular integration?

**Comment by Sebazzz** [comment]
Closed due to inactivity.

**Comment by xperiandri** [comment]
Just to be installable as an add-in from the store including SSO

**Comment by Sebazzz** [comment]
I will see what I can do, but no promises.

**Comment by xperiandri** [comment]
I tried to create some Azure DevOps extension myself but at that time there was no right API for my extension.
Then I saw a video of one guy who made a few extensions where he explains how to build and debug it. It is not as File/New Project... F5. But looks reasonably easy.

**Comment by xperiandri** [comment]
> I will see what I can do, but no promises.

Thanks in advance
